config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
	  get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
	  put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  get 'pages/home', to: 'high_voltage/pages#show', id: 'home'
	get 'pages/about', to: 'high_voltage/pages#show', id: 'about'
	get 'pages/directions', to: 'high_voltage/pages#show', id: 'directions'
	get 'pages/gus', to: 'high_voltage/pages#show', id: 'gus'
	get 'admin', to: 'contents#index', id: 'admin_home'
	authenticate :user do
		resources :contents
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update]
  before_action :authenticate_user!

  # GET /contents
  def index
    @contents = Content.all
  end

  # GET /contents/1
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  def create
    @content = Content.new(content_params)

    if @content.save
      redirect_to @content, notice: 'Content was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /contents/1
  def update
    if @content.update(content_params)
      redirect_to @content, notice: 'Content was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def content_params
      # params
      params.permit(:section, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	  <%= text_area_tag :content, content.content, :class => "tinymce", :rows => 12, :cols => 120 %>
  </div>
	
	<%= tinymce %>
	
	<div class="actions">
    <%= form.submit "Save", :class => 'btn btn-success' %>
		<%= link_to 'Back', contents_path, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div class="main">
	<div class="container container-fluid">
		<div class="row">
			<div class="col-sm-6">
				<h1>Editing Content</h1>
				<strong>Section:</strong> Content<br>
				
				<%= render 'form', content: @content %>
			</div>
		</div>
	</div>
</div>

app/views/contents/index.html.erb
<div class="main">
	<p id="notice"><%= notice %></p>
	
	<h1>Contents</h1>
	<div class="container">
		<div class="row">
			<table class="table">
				<thead>
				<tr>
					<th>Section</th>
					<th>Content</th>
					<th></th>
				</tr>
				</thead>
				
				<tbody>
				<% @contents.each do |content| %>
					<tr>
						<td><%= content.section %></td>
						<td><%= content.content %></td>
						<td><%= link_to 'Edit', edit_content_path(content) %></td>
					</tr>
				<% end %>
				</tbody>
			</table>
			
			<br>
		
		</div>
	</div>
</div>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Section:</strong>
  <%= @content.section %>
</p>

<p>
  <strong>Content:</strong>
  <%= @content.content %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/_footer.html.erb
<footer>
	<section class="twitter_feed_wrapper">
		<div class="container">
			<div class="row wow animated fadeInUp">
				<div class="twitter_feed_icon col-sm-1 col-md-1"><a href="https://www.facebook.com/woodburyflea/"><i class="fa fa-facebook" aria-hidden="true"></i></a></div>
				<div class="col-sm-11 col-md-11">
					<blockquote>
						<p>Like Us On Facebook  <a href="https://www.facebook.com/woodburyflea/">https://www.facebook.com/woodburyflea/</a></p>
						— The Woodbury Flea Market (@woodburyflea) <a href="https://www.facebook.com/woodburyflea/">April 16, 2015</a></blockquote>
				</div>
			</div>
		</div>
	</section>
	<section id="footer_teasers_wrapper">
		<div class="container">
			<div class="row">
				<div class="footer_teaser col-sm-4 col-md-4">
					<h3>Info</h3>
					<p><i class="fa fa-map-marker"></i> 44 Sherman Hill Rd</p>
					<p><i class="fa fa-phone"></i> (203) 263-6217</p>
					<p><i class="fa fa-envelope"></i>  thenewwoodburyfleamarket@gmail.com</p>
					<p>
						<a href="https://www.facebook.com/pages/Woodbury-Antiques-Flea-Market/194628543955095">
							<i class="fa fa-facebook"></i> Like Us on Facebook!
						</a>
					</p>
				</div>
				<div class="footer_teaser col-sm-4 col-md-4">
					<h3>Copyright</h3>
					Copyright The Woodbury Flea Market ©2018<br>
					Sherman Great Meadows LLC. all rights reserved<br>
					<% if user_signed_in? %>
						<a href="<%= admin_path %>">Admin</a> |
						<a href="<%= destroy_user_session_path %>" >Logout</a>
					<% else %>
						<%= link_to('Login', new_user_session_path) %>
					<% end %>

				</div>
				<div class="footer_teaser col-sm-4 col-md-4" id="latest-flickr-images">
					<h3>Website Developed by </h3>
					<a href="http://bluehelmet.software"><img src="<%= image_path "bluehelmet.png" %>" width="300" alt="Bluehelmet" /></a>
				</div>
			</div>
		</div>
	</section>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="container-fluid">
		<div class="navbar navbar-default" role="navigation">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">
					<img src="<%= image_path "wfm_logo.png" %>" alt="Wfm logo" />
					<!-- ><span class="logo_title">The Woodbury<strong>Antiques and Flea Market</strong></span>
					<span class="logo_subtitle">The best market in CT!</span>  -->
				</a>
				<a class="btn btn-navbar btn-default navbar-toggle" data-toggle="collapse"
				   data-target=".navbar-collapse"><span class="nb_left pull-left">
              <span class="fa fa-reorder"></span></span> <span class="nb_right pull-right">menu</span>
				</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav pull-right navbar-nav">
					
					<% if current_page?(root_path) %> <li class="active"><%= link_to('Home', root_url) %></li>
					<% else %><li><%= link_to('Home', root_url) %></li><% end %>
					
					<% if current_page?(pages_gus_path) %> <li class="active"><%= link_to('Gus', pages_gus_path) %></li>
					<% else %><li><%= link_to('Gus', pages_gus_path) %></li><% end %>
					
					<% if current_page?(pages_directions_path) %> <li class="active"><%= link_to('Directions', pages_directions_path) %></li>
					<% else %><li><%= link_to('Directions', pages_directions_path) %></li><% end %>
					
					<% if current_page?(pages_about_path) %> <li class="active"><%= link_to('About', pages_about_path) %></li>
					<% else %><li><%= link_to('About', pages_about_path) %></li><% end %>
					
					<% if user_signed_in? %>
						<li><a href="<%= admin_path %>">Admin</a></li>
						<li><a href="<%= destroy_user_session_path %>" >Logout</a></li>
					<% end %>
					
				</ul>
			</div>
		</div>
		<div id="social_media_wrapper"><a
			href="https://www.facebook.com/pages/Woodbury-Antiques-Flea-Market/194628543955095"><i
			class="fa fa-facebook"></i></a>
			<a href="http://bluehelmet.software"><i class="fa fa-flickr"></i></a></div>
		<!-- div id="sign"><a href="register.html"><i class="fa fa-user"></i><span>Register/Sign in</span></a></div> -->
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<!--	  <meta charset="utf-8">-->
	<!--	  <meta http-equiv="x-ua-compatible" content="ie=edge">-->
	<!--	  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
	<!--	  <title>Home</title>-->
	<meta charset="utf-8">
	<meta name="description" content="The Woodbury Antiques and Flea Market is the largest CT flea market in 2018">
	<link rel="canonical" href="http://www.woodburyflea.net/">
	
	<meta property="og:locale" content="en_US">
	<meta property="og:type" content="website">
	<meta property="og:title" content="Home | The Woodbury Antiques and Flea Market">
	<meta property="og:url" content="http://www.woodburyflea.net">
	<meta property="og:site_name" content="The Woodbury Antiques and Flea Market">
	<meta name="twitter:card" content="The best CT Flea Market in 2018">
	<meta name="twitter:title" content="Home | The New Woodbury Flea Market">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= favicon_link_tag %>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	
	<%= stylesheet_link_tag 'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	
	<%= stylesheet_link_tag 'animate.css' %>
	<%= stylesheet_link_tag 'flexslider.css' %>
	<%= stylesheet_link_tag 'prettyPhoto.css' %>
	<%= stylesheet_link_tag 'theme.css' %>
	<%= stylesheet_link_tag 'style.css' %>
	<%= tinymce_assets %>
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,600italic,700,700italic,300italic" rel="stylesheet"/>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<%#= stylesheet_link_tag 'bootstrap.min.css', media: 'all' %>

</head>

<body>
	<%= render 'layouts/header' %>
	
	<% flash.each do |type, msg| %>
		<div class="alert alert-<%= type %>">
			<%= msg %>
		</div>
	<% end %>
	
	<%= yield %>
	
	<%= render 'layouts/footer' %>
</body>

<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<%= javascript_include_tag 'bootstrap.min.js' %>
<%= javascript_include_tag 'woothemes-FlexSlider-06b12f8/jquery.flexslider-min.js' %>
<%= javascript_include_tag 'prettyPhoto_3.1.5/jquery.prettyPhoto.js' %>
<%= javascript_include_tag 'isotope/jquery.isotope.min.js' %>
<%#= javascript_include_tag 'jquery.ui.totop.js' %>
<%= javascript_include_tag 'easing.js' %>
<%= javascript_include_tag 'wow.min.js' %>
<%= javascript_include_tag 'snap.svg-min.js' %>
<%= javascript_include_tag 'restart_theme.js' %>
<%= javascript_include_tag 'collapser.js' %>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-115473189-1"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-36641202-1"></script>
<%= javascript_include_tag 'google_analytics.js' %>
<%= javascript_include_tag 'privy.js' %>
<%= javascript_include_tag 'modernizr.js' %>

</html>

app/views/pages/about.html.erb
<div class="main">
	<div class="container">
		<section class="hgroup">
			<h1>About us</h1>
			
			<ul class="breadcrumb pull-right">
				<li><%= link_to 'Home', '/' %></li>
				<li class="active">About us</li>
			</ul>
		
		</section>
		<section class="article-text">
			<div class="row">
				<div class=".col-xs-12 .col-sm-6 .col-lg-8">
					<div class="lead">
						<p>
							The Woodbury Antiques and Flea Market has grown to become one of the the best kept secrets in CT. We are a
							smaller flea market in Woodbury, CT. The flea market focusses on it's role as an antiques market first,
							utilizing our location in the Woodbury, The Antique Capital.<br>
							Vendors at The Woodbury Flea Market sell every type of goods. From Antiques, to furniture, electronics,
							clothing and much much more. Stop by one weekend to check us out!
						</p>
						<hr>
						<p>Gus and Ann Kaloidis took over the old Woodbury Antiques and Flea Market in 2008 and have been running it
							as a family business ever since. We have dealers offering a variety of merchandise for sale with an
							emphasis on early items and antiques. The market is open every Saturday.<br>
						</p>
						<p>Vendors can drive to their assigned spaces and set up their tables at 6:30 am. Reservations are not
							required, walk-ins are welcome, but you may call us to let us know you are coming at: (203) 263-6217. Ask
							management for special rates.</p>
						
						<p>Customers are invited after 7:30 A.M. We offer ample parking around the restaurant. Parking attendents
							are available to assist you. Admission is FREE and handicap parking is also available.</p>
						
						<p>This is a continuation of the old Woodbury Antiques and Flea market from around the corner (Route 63
							Middle Quarter Road), that had been in business for over forty years. Don and Diane Heavens owned and
							operated the market until they sold their property in 2006.</p>
						
						<p>The Market is easily accessible from I-84 and it is one and one- half hours away from NY City. The
							nearest airports are Oxford and Danbury. The Market is located at the bottom of Sherman Hill Road near the
							intersection of routes 6 and 64.</p>
						
						<p>Woodbury is known for its old houses, antique shops and restaurants. Visitors come from all over every
							weekend, especially from New York.</p>
						<p>Come and enjoy the day!!</p></div>
					<br>
					<iframe
						src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2986.893108324172!2d-73.20062!3d41.528256!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e7eebe87b31df9%3A0x75b3f1c198d36c1b!2sThe+Woodbury+Flea+Market!5e0!3m2!1sen!2sus!4v1431043945411"
						width="600" height="450" frameborder="0" style="border:0"></iframe>
					<h2>Reservations: (203)263-6217, or arrive Saturday at 6:30am (weather permitting, check back for updates)</h2>
					<br>
				</div>
			</div>
		</section>
	
	
	</div>
</div>

app/views/pages/directions.html.erb
<div class="main">
	<div class="container">
		<section class="hgroup">
			<h1>Come Visit The Woodbury Flea Market</h1>
			<h2>44 Sherman Hill Rd. Woodbury, CT 06798</h2>
			<h2>(203) 263 - 6217</h2>
			<h2><a href="mailto:thenewwoodburyfleamarket@gmail.com">thenewwoodburyfleamarket@gmail.com</a></h2>
			<ul class="breadcrumb pull-right">
				<li><%= link_to 'Home', '/' %></li>
				<li class="active">About us</li>
			</ul>
		</section>
		<section class="article-text">
			<div class="row">
				<div class=".col-xs-12 .col-sm-6 .col-lg-8">
					<div class="lead">
					</div>
					<br>
					<iframe
						src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2986.893108324172!2d-73.20062!3d41.528256!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89e7eebe87b31df9%3A0x75b3f1c198d36c1b!2sThe+Woodbury+Flea+Market!5e0!3m2!1sen!2sus!4v1431043945411"
						width="600" height="450" frameborder="0" style="border:0"></iframe>
					<h2>Reservations: (203)263-6217, or arrive Saturday at 6:30am (weather permitting, check back for updates)</h2>
					<br>
				</div>
			</div>
		</section>
	</div>
</div>

app/views/pages/gus.html.erb
<div class="main">
	<div class="container">
		<section class="hgroup">
			<h1>About The Owner</h1>
			<h2>Gus Kaloidis </h2>
			
			<ul class="breadcrumb pull-right">
				<li><%= link_to 'Home', '/' %></li>
				<li class="active">About the Owner</li>
			</ul>
		
		</section>
		<section class="article-text">
			<div class="row">
				<div class="col-sm-8 col-md-8">
					<div class="lead"><br>
						<p>Gus Kaloidis had been in the restaurant business in Woodbury for over 40 years until he sold his restaurant (Elenni's/ Woodbury Pizza Castle) in 2006. The Flea Market is his latest venture and he is very happy to be back in business in Woodbury serving the public.</p>
						
						<p>Gus is a former airline pilot and his passion has always been flying. He has been a resident of Woodbury for over forty years and is a member of the Woodbury Lions Club. He runs the flea market with his wife Ann and his three children, Vas, Chrysanthe and Maria Eleni.</p>
					</div>
					<p class="columns_2">
						<blockquote>
					<p>
						<i class="fa fa-envelope"></i> <a href="mailto:thenewwoodburyfleamarket@gmail.com">thenewwoodburyfleamarket@gmail.com</a> <br><br>
						<i class="fa fa-phone"> (203) 263-6217 </i>
					</p>
					<small>Contact us to reserve a spot!</small>
					</blockquote>
				</div>
				<div class="col-sm-4 col-md-4">
					<div class="service_teaser vertical">
						<div class="service_photo">
							<figure style="background-image:url(<%= image_path "gus.jpg" %>)"></figure>
						</div>
						<div class="service_details">
							<h2 class="section_header skincolored"><b>Gus Kaloidis</b>
								<small>Owner</small>
							</h2>
							<a class="btn btn-primary" href="mailto:thenewwoodburyfleamarket@gmail.com">E-Mail <i class="fa fa-envelope"></i></a>
						</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>

app/views/pages/home.html.erb
<section id="slider_wrapper" class="slider_wrapper full_page_photo">
  <div id="main_flexslider" class="flexslider">
    <ul class="slides">
      <li class="item" style="background-image: url(<%= image_path("/sliders/market1.jpg") %>">
        <div class="container">
          <div class="carousel-caption">
            <h1 class="skincolored">Every <strong>Saturday</strong> <br></h1>
          </div>
        </div>
      </li>
      <li class="item" style="background-image: url(<%= image_path("/sliders/market2.jpg") %>">
        <div class="container">
          <div class="carousel-caption">
            <h1>Customers are <strong>Always Free</strong></h1>
          </div>
        </div>
      </li>
      <li class="item" style="background-image: url(<%= image_path("/sliders/market3.jpg") %>)">
        <div class="container">
          <div class="carousel-caption">
            <h1 class="skincolored">The <strong>best vendor rates</strong> in CT!</h1>
          </div>
        </div>
      </li>

    </ul>
  </div>
</section>
<div class="main">
  <div class="container-fluid">
    <br>
    <section class="call_to_action">
      <h2>
        <center><i class="fa fa-flag-checkered"></i></center>
        <%= Content.find_by(section: "home").content.html_safe %>
      </h2>

      <h2>We are open for the 2023 season!!<br> Check back for updates!</h2>
      <br>
      <center>
        <span class="dot"></span>
        <span class="dot"></span>
        <span class="dot"></span>
      </center>
      <br>

      <h1>Come visit The Woodbury CT Antiques and Flea Market</h1><br>

      <h4>Every Saturday (weather permitting) we are open from 7:30AM - 2:30PM</h4>

      <br>
      <center>
        <span class="dot"></span>
        <span class="dot"></span>
        <span class="dot"></span>
      </center>
      <br>
      <h1>Vendors</h1>
      <h4>Interested in becoming a vendor? Please arrive anytime after 6:30AM.</h4>
      <h4>The fee to rent a <strong>20 foot (length) space is only $30!</strong></h4>
      <h4>Please Note: No pets allowed (with the exception of service animals).</h4>
      <br>
      <h4>We are located at <strong>44 Sherman Hill Rd. Woodbury, CT. 06798</strong></h4>
      <br>
      <div>
        <span style="color: inherit; font-family: inherit; font-size: 18px; line-height: 1.1;">For more information please call: (203) 263-6217, email:</span>
        <a href="mailto:thenewwoodburyfleamarket@gmail.com" style="font-family: inherit; font-size: 18px; line-height: 1.1; background-color: rgb(255, 255, 255);">thenewwoodburyfleamarket@gmail.com</a>
        <span style="color: inherit; font-family: inherit; font-size: 18px; line-height: 1.1;">, or </span>
        <a href="https://www.facebook.com/woodburyflea/" style="font-family: inherit; font-size: 18px; line-height: 1.1; background-color: rgb(255, 255, 255);">like
          us on Facebook!</a>
      </div>
      <br>

      <a href="<%= pages_directions_path %>" class="btn btn-primary btn-lg">Get Directions!</a>
      <a href="https://www.facebook.com/woodburyflea/" class="btn btn-success btn-lg">Facebook Message Us!</a>
    </section>
    <section class="features_teasers_wrapper">
      <div class="row">
        <div class="feature_teaser col-sm-4 col-md-4">
          <h1><i class="fa fa-map-marker" aria-hidden="true"></i></h1>
          <p>
          <h3>Location</h3>
          <address>
            <strong>The Woodbury Flea Market</strong><br>
            4 Sherman Hill Road (RT64)<br>
            Woodbury CT, 06798<br>
            <abbr title="phone"> (203) 263-6217 </abbr>
          </address>
        </div>
        <div class="feature_teaser col-sm-4 col-md-4">
          <h1><i class="fa fa-group fa-2"></i></h1>
          <h3>Vendors</h3>
          <p>To become a vendor Contact us or just drive in after 6:00 AM any Saturday (weather permitting, check back for updates) and you will be given a
            space 25ft (long) to set up your table</p>
        </div>
        <div class="feature_teaser col-sm-4 col-md-4">
          <h1><i class="fa fa-user fa-2"></i></h1>
          <h3>About the Owner</h3>
          <p>Gus Kaloidis has been in the restaurant business for almost forty years, until he sold his last
            restaurant (Elenni's) six years ago. <a href="<%= pages_gus_path %>"><small>More...</small></a></p>
        </div>
      </div>
    </section>
  </div>
</div>